name: "This is hello action"
description: "sey hello with git atcions"


inputs:
  firstGreeting:
    description: "who would you like to greet in the console"
    required: true
    default: Hubolt

  secondGreeting: 
    description: "another person to greet"
    required: true
    default: Mona with Ocatcat

  thirdGreeting:
    description: "a third greeting"
    required: false

runs:
  using: docker
  image: Dockerfile
