name: "issue maker"
description: "create and issue with a cat fact as the body"

inputs:
  issueTitle:
    description: "A name for the cat-fact issue"
    required: true
    default: "a cat fact for you"

  catFact:
    description: "The cat fact retrived from a previous action"
    required: true
    defaault: "Mona is an Octocat"

  repoToken:
    description: "Authentyfication token, use secrets.GITHUB_TOKEN"
  
runs:
  using: docker
  image: Dockerfile
